<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYMbFlt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYMbFlt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYMbFlt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYMbFlt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTYMbFlt\App_KernelDevDebugContainer([
    'container.build_hash' => 'TYMbFlt',
    'container.build_id' => '8c7a47ba',
    'container.build_time' => 1599465561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYMbFlt');
