<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXEd0lx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXEd0lx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXEd0lx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXEd0lx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXEd0lx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXEd0lx',
    'container.build_id' => '70c189a6',
    'container.build_time' => 1600071871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXEd0lx');
