<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDyzuw2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDyzuw2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDyzuw2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDyzuw2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDyzuw2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dyzuw2x',
    'container.build_id' => 'fae1c92c',
    'container.build_time' => 1599471267,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDyzuw2x');
